config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :home do
    collection do
      post :napthe
      get :rut_tien
      get :nap_tien
      get :chuyen_tien
    end
  end
  resources :orders do
    collection do
      get :get_users
    end
  end
  namespace :admin do
    resources :transaction
    resources :dashboard
    resources :users
    resources :orders do
      collection do
        get :list_pending_doi_the
        get :list_pending_rut_tien
      end
      member do
        post :doi_the_success
        post :doi_the_fail
        post :order_fail
        post :order_success
      end
    end
    root 'dashboard#index'

  end
  match 'history', to: 'users#history', via: [:get]
  match 'profile', to: 'users#profile', via: [:get]
  match 'nap-tien', to: 'users#nap_tien', via: [:get]
  match 'rut-tien', to: 'users#rut_tien', via: [:get]
  match 'chuyen-tien', to: 'users#chuyen_tien', via: [:get]
  match 'xac-nhan-chuyen-tien', to: 'users#xac_nhan_chuyen_tien', via: [:post]
  
  root 'home#index'
end

app/views/admin/shared/_head.html.erb
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1" />

<!-- GOOGLE FONTS -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500" rel="stylesheet" />
<link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet" />

app/views/admin/shared/_header.html.erb
  <header class="main-header " id="header">
    <nav class="navbar navbar-static-top navbar-expand-lg">
      <!-- Sidebar toggle button -->
      <button id="sidebar-toggler" class="sidebar-toggle">
      <span class="sr-only">Toggle navigation</span>
      </button>
      <!-- search form -->
      <div class="search-form d-none d-lg-inline-block">
        <div class="input-group">
          <button type="button" name="search" id="search-btn" class="btn btn-flat">
          <i class="mdi mdi-magnify"></i>
          </button>
          <input type="text" name="query" id="search-input" class="form-control" placeholder="'button', 'chart' etc."
            autofocus autocomplete="off" />
        </div>
        <div id="search-results-container">
          <ul id="search-results"></ul>
        </div>
      </div>
      <div class="navbar-right ">
        <ul class="nav navbar-nav">
          <li class="dropdown notifications-menu">
            <button class="dropdown-toggle" data-toggle="dropdown">
            <i class="mdi mdi-bell-outline"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-header">You have 5 notifications</li>
              <li>
                <a href="#">
                <i class="mdi mdi-account-plus"></i> New user registered
                <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 10 AM</span>
                </a>
              </li>
              <li>
                <a href="#">
                <i class="mdi mdi-account-remove"></i> User deleted
                <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 07 AM</span>
                </a>
              </li>
              <li>
                <a href="#">
                <i class="mdi mdi-chart-areaspline"></i> Sales report is ready
                <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 12 PM</span>
                </a>
              </li>
              <li>
                <a href="#">
                <i class="mdi mdi-account-supervisor"></i> New client
                <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 10 AM</span>
                </a>
              </li>
              <li>
                <a href="#">
                <i class="mdi mdi-server-network-off"></i> Server overloaded
                <span class=" font-size-12 d-inline-block float-right"><i class="mdi mdi-clock-outline"></i> 05 AM</span>
                </a>
              </li>
              <li class="dropdown-footer">
                <a class="text-center" href="#"> View All </a>
              </li>
            </ul>
          </li>
          <!-- User Account -->
          <li class="dropdown user-menu">
            <button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
            <%= image_tag  "logo.jpg", class: "user-image" %>
            <span class="d-none d-lg-inline-block">Admin</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right">
              <!-- User image -->
              <li class="dropdown-header">
                <%= image_tag  "logo.jpg", class: "img-circle" %>
                <div class="d-inline-block">
                  <%= current_user.email %> <small class="pt-1"> <%= current_user.email %></small>
                </div>
              </li>
              <li>
                <a href="user-profile.html">
                <i class="mdi mdi-account"></i> My Profile
                </a>
              </li>
              <li>
                <a href="#">
                <i class="mdi mdi-email"></i> Message
                </a>
              </li>
              <li>
                <a href="#"> <i class="mdi mdi-diamond-stone"></i> Projects </a>
              </li>
              <li class="right-sidebar-in">
                <a href="javascript:0"> <i class="mdi mdi-settings"></i> Setting </a>
              </li>
              <li class="dropdown-footer">
                <a href="/"> <i class="mdi mdi-logout"></i> Log Out </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

app/views/admin/shared/_navbar.html.erb
<aside class="left-sidebar bg-sidebar">
  <div id="sidebar" class="sidebar sidebar-with-footer">
    <!-- Aplication Brand -->
    <div class="app-brand">
      <a href="/admin" title="Dashboard">
        <svg
          class="brand-icon"
          xmlns="http://www.w3.org/2000/svg"
          preserveAspectRatio="xMidYMid"
          width="30"
          height="33"
          viewBox="0 0 30 33"
          >
          <g fill="none" fill-rule="evenodd">
            <path
              class="logo-fill-blue"
              fill="#7DBCFF"
              d="M0 4v25l8 4V0zM22 4v25l8 4V0z"
              />
            <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z" />
          </g>
        </svg>
        <span class="brand-name text-truncate"> Dashboard</span>
      </a>
    </div>
    <!-- begin sidebar scrollbar -->
    <div class="sidebar-scrollbar">
      <!-- sidebar menu -->
      <ul class="nav sidebar-inner" id="sidebar-menu">

        <li  class="has-sub active expand" >
          <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#orders-nav"
            aria-expanded="false" aria-controls="orders-nav">
          <i class="mdi mdi-view-dashboard-outline"></i>
          <span class="nav-text"> Đơn hàng</span> <b class="caret"></b>
          </a>
          <ul  class="collapse show"  id="orders-nav"
            data-parent="#sidebar-menu">
            <div class="sub-menu">
              <li  class="" >
                <%= item_link_nav("Đơn hàng", admin_orders_path, class: "sidenav-item-link") %>
              </li>
              <li  class="" >
                <%= item_link_nav("Thẻ chờ xử lý", list_pending_doi_the_admin_orders_path, class: "sidenav-item-link") %>
              </li>
              <li  class="" >
                <%= item_link_nav("Yêu cầu thanh toán", list_pending_rut_tien_admin_orders_path, class: "sidenav-item-link") %>
              </li>
              <li  class="" >
              </li>
            </div>
          </ul>
        </li>

        <li  class="has-sub " >
          <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#dashboard"
            aria-expanded="false" aria-controls="dashboard">
          <i class="mdi mdi-view-dashboard-outline"></i>
          <span class="nav-text">Manage</span> <b class="caret"></b>
          </a>
          <ul  class="collapse"  id="dashboard"
            data-parent="#sidebar-menu">
            <div class="sub-menu">
              <li  class="" >
                <%= item_link_nav("User", admin_users_path, class: "sidenav-item-link") %>
              </li>
              <li  class="" >
                <%= item_link_nav("Transaction", "admin_websites_path", class: "sidenav-item-link") %>
              </li>
              <li  class="" >
              </li>
            </div>
          </ul>
        </li>

      </ul>
    </div>
    <div class="sidebar-footer">
      <hr class="separator mb-0" />
      <div class="sidebar-footer-content">
        
      </div>
    </div>
  </div>
</aside>

app/views/admin/shared/_thong_bao.html.erb
<div id="thongbao" class="modal fade in" tabindex="-1" role="dialog" >
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Thông Báo</h4>
      </div>
      <div class="modal-body">
	   <p>THÔNG BÁO HỆ THỐNG
- UPDATE API TƯ ĐỘNG DUYỆT THẺ VIETTEL, MOBI 24/24 !!!</p>
	   <p>- <span style="color: #ff0000;">Gửi sai mệnh giá sẽ mất 100% thẻ, vì vậy hãy nhìn lại mệnh giá 1 lần nữa trước khi bấm GỬI THẺ tránh mất tiền</span></p>
     <p>- <span style="color: #ff0000;">Nạp sai mệnh giá và sai quá nhiều lần và có hành vi spam sẽ bị hủy thẻ.Vi phạm nhiều = Banned</span></p>
     <p>- <span style="color: #ff0000;">Lưu Ý: Santhe86  Ko Chịu Trách Nhiệm Dưới Mọi Hình Thức Đối Với Các Hình Thức Giả Mạo Trên FaceBook.Hãy Nhớ Kĩ Thông Tin Khi Vào Website Tránh Trường Hợp Bị Các Đối Tượng Xấu Lừa CK Mà Ko Phải STK Từ Thesieunhanh</span></p>
     <p>- <span style="color: #ff0000;"> Nhằm nâng cao hệ thống, nếu gặp lỗi quý khách vui lòng liên hệ  FB ADMIN Nguyễn Đăng Tín
AE Nạp tiền Vào TK LH ZALO 096.196.36.36 </span></p>  
   <p>- <span style="color: #ff0000;"> Vấn đề đại lý phân phối thẻ cào vui lòng liên hệ 096.196.36.36</span></p>  

   <p>- <span style="color: #ff0000;"> Vấn đề nạp thẻ cào lỗi, sai vui lòng liên hệ : 096.196.36.36 </span></p>  
   <p>- <span style="color: #ff0000;"> KẾT BẠN HOẶC THEO DÕI FB ADMIN ĐỂ NHẬN THÔNG BÁO SỚM NHẤT !</span></p>
   <p>- <span style="color: #ff0000;"> GIỜ LÀM VIỆC TỪ 08:00-20:00 HẰNG NGÀY</span></p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $('#thongbao').modal('show')
  })
</script>